"""empty message

Revision ID: 93c2cbe453ef
Revises: 5f77b20b2cf3
Create Date: 2026-04-30 19:53:33.793489

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '93c2cbe453ef'
down_revision: Union[str, None] = '5f77b20b2cf3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_question_progress_id'), table_name='question_progress')
    op.drop_table('question_progress')
    op.add_column('tasks', sa.Column('created_by', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'tasks', 'users', ['created_by'], ['id'])
    op.drop_column('tasks', 'id;description;task_subgroup_id;question;answer;failed_answer')
    op.add_column('users', sa.Column('is_admin', sa.Boolean(), nullable=True))
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_column('users', 'updated_at')
    op.drop_column('users', 'email')
    op.drop_column('users', 'is_active')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('email', sa.VARCHAR(length=100), autoincrement=False, nullable=False))
    op.add_column('users', sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.drop_column('users', 'is_admin')
    op.add_column('tasks', sa.Column('id;description;task_subgroup_id;question;answer;failed_answer', sa.VARCHAR(length=256), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'tasks', type_='foreignkey')
    op.drop_column('tasks', 'created_by')
    op.create_table('question_progress',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('question_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('status', postgresql.ENUM('KNOW', 'ALMOST_KNOW', 'DONT_KNOW', name='knowledgestatus'), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['question_id'], ['tasks.id'], name=op.f('question_progress_question_id_fkey')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('question_progress_user_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('question_progress_pkey'))
    )
    op.create_index(op.f('ix_question_progress_id'), 'question_progress', ['id'], unique=False)
    # ### end Alembic commands ###
