version: '3.8'

services:
  web:
    build: .
    ports:
      - "8080:8080"
    volumes:
      - .:/app
      - ./static:/app/static
      - ./templates:/app/templates
    environment:
      - DATABASE_URL=postgresql://admin:admin@217.198.12.151:5432/users
      - SECRET_KEY=your-secret-key-change-in-production
    develop:
      watch:
        - action: sync
          path: .
          target: /app
        - action: rebuild
          path: requirements.txt
